const fs = require('fs');

const GSPN_COLUMNS = [
  'Date',
  'Branch Name',
  'No',
  'Service Order No.',
  'ASC Job No',
  'Created',
  'Assigned',
  'Assigned Time',
  'Model',
  'Serial',
  'Wty Status',
  'VOC',
  'REDO',
  'Risk Sensing',
  'RED',
  'High Priority',
  'Customer Name',
  'City',
  'App Date',
  'App Time',
  'Service Type',
  'Status',
  'Reason',
  'B2B',
  'Risk Reason'
];

const sampleRows = [
  {
    'Date': '11.09.2026',
    'Branch Name': 'Gurgaon-CE',
    'No': 1,
    'Service Order No.': '4293847291',
    'ASC Job No': '4903753-01',
    'Created': '11.09.2026',
    'Assigned': '11.09.2026',
    'Assigned Time': '10:15',
    'Model': 'AR18CY3AQUN',
    'Serial': 'SN987654321',
    'Wty Status': 'In Warranty',
    'VOC': 'Cooling issue / Low cooling in high ambient',
    'REDO': 'N',
    'Risk Sensing': 'Normal',
    'RED': 'N',
    'High Priority': 'High',
    'Customer Name': 'Rajesh Sharma',
    'City': 'Gurgaon',
    'App Date': '11.09.2026',
    'App Time': '14:00 - 16:00',
    'Service Type': 'IH',
    'Status': 'Engineer Assigned',
    'Reason': 'Appointment Fixed with customer',
    'B2B': 'N',
    'Risk Reason': 'None'
  },
  {
    'Date': '11.09.2026',
    'Branch Name': 'Gurgaon-CE',
    'No': 2,
    'Service Order No.': '4293847292',
    'ASC Job No': '4903753-02',
    'Created': '06.09.2026',
    'Assigned': '06.09.2026',
    'Assigned Time': '11:30',
    'Model': 'WA65T4262GG',
    'Serial': 'SN987654322',
    'Wty Status': 'Out of Warranty',
    'VOC': 'Drain motor error / water not draining',
    'REDO': 'Y',
    'Risk Sensing': 'High',
    'RED': 'Y',
    'High Priority': 'High',
    'Customer Name': 'Anita Verma',
    'City': 'Gurgaon',
    'App Date': '07.09.2026',
    'App Time': '11:00 - 13:00',
    'Service Type': 'IH',
    'Status': 'Part Pending',
    'Reason': 'Part awaited from central warehouse',
    'B2B': 'N',
    'Risk Reason': 'Repeat repair within 30 days'
  },
  {
    'Date': '11.09.2026',
    'Branch Name': 'Gurgaon-CE',
    'No': 3,
    'Service Order No.': '4293847293',
    'ASC Job No': '4903753-03',
    'Created': '01.09.2026',
    'Assigned': '01.09.2026',
    'Assigned Time': '14:00',
    'Model': 'QA55Q60AAK',
    'Serial': 'SN987654323',
    'Wty Status': 'In Warranty',
    'VOC': 'Horizontal lines on panel',
    'REDO': 'N',
    'Risk Sensing': 'Normal',
    'RED': 'N',
    'High Priority': 'Normal',
    'Customer Name': 'Sunil Kumar',
    'City': 'Manesar',
    'App Date': '02.09.2026',
    'App Time': '16:00 - 18:00',
    'Service Type': 'Initial Installation',
    'Status': 'Pending',
    'Reason': 'Customer requested rescheduled visit',
    'B2B': 'N',
    'Risk Reason': 'None'
  },
  {
    'Date': '11.09.2026',
    'Branch Name': 'Ahmedabad-CE',
    'No': 4,
    'Service Order No.': '4293847294',
    'ASC Job No': '4903754-01',
    'Created': '28.08.2026',
    'Assigned': '28.08.2026',
    'Assigned Time': '09:45',
    'Model': 'RT28T3722S8',
    'Serial': 'SN987654324',
    'Wty Status': 'Out of Warranty',
    'VOC': 'Not cooling / Compressor buzzing sound',
    'REDO': 'N',
    'Risk Sensing': 'Normal',
    'RED': 'N',
    'High Priority': 'Normal',
    'Customer Name': 'Pradeep Patel',
    'City': 'Ahmedabad',
    'App Date': '29.08.2026',
    'App Time': '10:00 - 12:00',
    'Service Type': 'IH',
    'Status': 'Estimate Sent',
    'Reason': 'Estimate pending approval from customer',
    'B2B': 'N',
    'Risk Reason': 'None'
  },
  {
    'Date': '11.09.2026',
    'Branch Name': 'Ahmedabad-CE',
    'No': 5,
    'Service Order No.': '4293847295',
    'ASC Job No': '4903754-02',
    'Created': '20.08.2026',
    'Assigned': '20.08.2026',
    'Assigned Time': '15:20',
    'Model': 'MC28H5015AK',
    'Serial': 'SN987654325',
    'Wty Status': 'In Warranty',
    'VOC': 'Touch panel not responding / key error',
    'REDO': 'N',
    'Risk Sensing': 'High',
    'RED': 'Y',
    'High Priority': 'High',
    'Customer Name': 'Meena Shah',
    'City': 'Gandhinagar',
    'App Date': '21.08.2026',
    'App Time': '12:00 - 14:00',
    'Service Type': 'Carry In',
    'Status': 'Part Pending',
    'Reason': 'PCB main board on back order',
    'B2B': 'N',
    'Risk Reason': 'Aging over 15 days escalation'
  },
  {
    'Date': '11.09.2026',
    'Branch Name': 'Surat-CE',
    'No': 6,
    'Service Order No.': '4293847296',
    'ASC Job No': '9225951-01',
    'Created': '10.08.2026',
    'Assigned': '10.08.2026',
    'Assigned Time': '11:00',
    'Model': 'DW60M9550FS',
    'Serial': 'SN987654326',
    'Wty Status': 'In Warranty',
    'VOC': 'Water leakage from bottom / Error 4C',
    'REDO': 'N',
    'Risk Sensing': 'High',
    'RED': 'Y',
    'High Priority': 'High',
    'Customer Name': 'Bhavik Desai',
    'City': 'Surat',
    'App Date': '11.08.2026',
    'App Time': '15:00 - 17:00',
    'Service Type': 'IH',
    'Status': 'Inspection Done',
    'Reason': 'Commercial unit / Technical team review',
    'B2B': 'Y',
    'Risk Reason': 'Critical aging 30+ days'
  },
  {
    'Date': '11.09.2026',
    'Branch Name': 'Surat-CE',
    'No': 7,
    'Service Order No.': '4293847297',
    'ASC Job No': '9225951-02',
    'Created': '11.09.2026',
    'Assigned': '11.09.2026',
    'Assigned Time': '12:10',
    'Model': 'WW80T504DAX',
    'Serial': 'SN987654327',
    'Wty Status': 'In Warranty',
    'VOC': 'Demo and installation request',
    'REDO': 'N',
    'Risk Sensing': 'Normal',
    'RED': 'N',
    'High Priority': 'Normal',
    'Customer Name': 'Pooja Mehta',
    'City': 'Surat',
    'App Date': '12.09.2026',
    'App Time': '10:00 - 12:00',
    'Service Type': 'Demonstration',
    'Status': 'Appointment Fixed',
    'Reason': 'Engineer scheduled for demo',
    'B2B': 'N',
    'Risk Reason': 'None'
  },
  {
    'Date': '11.09.2026',
    'Branch Name': 'Lucknow-HHP',
    'No': 8,
    'Service Order No.': '4293847298',
    'ASC Job No': '4903755-01',
    'Created': '09.09.2026',
    'Assigned': '09.09.2026',
    'Assigned Time': '16:30',
    'Model': 'SM-S928B',
    'Serial': 'SN987654328',
    'Wty Status': 'In Warranty',
    'VOC': 'Display flickering / S-Pen disconnect',
    'REDO': 'N',
    'Risk Sensing': 'Normal',
    'RED': 'N',
    'High Priority': 'Normal',
    'Customer Name': 'Mohd Tariq',
    'City': 'Lucknow',
    'App Date': '10.09.2026',
    'App Time': '11:00 - 13:00',
    'Service Type': 'Carry In',
    'Status': 'Under Repair',
    'Reason': 'Software update and calibration in progress',
    'B2B': 'N',
    'Risk Reason': 'None'
  },
  {
    'Date': '11.09.2026',
    'Branch Name': 'Lucknow-CE',
    'No': 9,
    'Service Order No.': '4293847299',
    'ASC Job No': '4903756-01',
    'Created': '03.09.2026',
    'Assigned': '03.09.2026',
    'Assigned Time': '10:00',
    'Model': 'AR12CY5AMWK',
    'Serial': 'SN987654329',
    'Wty Status': 'Out of Warranty',
    'VOC': 'Gas leakage / cooling coil replacement',
    'REDO': 'N',
    'Risk Sensing': 'Normal',
    'RED': 'N',
    'High Priority': 'Normal',
    'Customer Name': 'Sanjay Shukla',
    'City': 'Lucknow',
    'App Date': '04.09.2026',
    'App Time': '14:00 - 16:00',
    'Service Type': 'IH',
    'Status': 'Part Pending',
    'Reason': 'Copper coil part requisition submitted',
    'B2B': 'N',
    'Risk Reason': 'None'
  },
  {
    'Date': '11.09.2026',
    'Branch Name': 'Moradabad-HHP',
    'No': 10,
    'Service Order No.': '4293847300',
    'ASC Job No': '4903757-01',
    'Created': '11.09.2026',
    'Assigned': '11.09.2026',
    'Assigned Time': '13:45',
    'Model': 'SM-A546E',
    'Serial': 'SN987654330',
    'Wty Status': 'In Warranty',
    'VOC': 'Battery draining fast / overheating',
    'REDO': 'N',
    'Risk Sensing': 'Normal',
    'RED': 'N',
    'High Priority': 'Normal',
    'Customer Name': 'Deepak Rastogi',
    'City': 'Moradabad',
    'App Date': '11.09.2026',
    'App Time': '15:00 - 17:00',
    'Service Type': 'Carry In',
    'Status': 'Under Diagnosis',
    'Reason': 'Battery drain test under observation',
    'B2B': 'N',
    'Risk Reason': 'None'
  },
  {
    'Date': '11.09.2026',
    'Branch Name': 'Ghaziabad-CE',
    'No': 11,
    'Service Order No.': '4293847301',
    'ASC Job No': '4903758-01',
    'Created': '29.08.2026',
    'Assigned': '29.08.2026',
    'Assigned Time': '11:15',
    'Model': 'QA65QN90AAK',
    'Serial': 'SN987654331',
    'Wty Status': 'In Warranty',
    'VOC': 'No sound from HDMI eARC / optical out',
    'REDO': 'N',
    'Risk Sensing': 'High',
    'RED': 'N',
    'High Priority': 'High',
    'Customer Name': 'Vikramaditya Rao',
    'City': 'Ghaziabad',
    'App Date': '30.08.2026',
    'App Time': '14:00 - 16:00',
    'Service Type': 'IH',
    'Status': 'Technician Visit Scheduled',
    'Reason': 'Senior tech assistance needed',
    'B2B': 'N',
    'Risk Reason': 'Aging 11-14 days'
  },
  {
    'Date': '11.09.2026',
    'Branch Name': 'Cochin-CE',
    'No': 12,
    'Service Order No.': '4293847302',
    'ASC Job No': '4903759-01',
    'Created': '05.08.2026',
    'Assigned': '05.08.2026',
    'Assigned Time': '10:30',
    'Model': 'RS74T5001B4',
    'Serial': 'SN987654332',
    'Wty Status': 'In Warranty',
    'VOC': 'Freezer defrost sensor failure / Error 22E',
    'REDO': 'Y',
    'Risk Sensing': 'High',
    'RED': 'Y',
    'High Priority': 'High',
    'Customer Name': 'Thomas Mathew',
    'City': 'Ernakulam',
    'App Date': '06.08.2026',
    'App Time': '11:00 - 13:00',
    'Service Type': 'Stock Repair',
    'Status': 'Part Pending',
    'Reason': 'Defrost heater imported spare delivery delayed',
    'B2B': 'N',
    'Risk Reason': 'Critical aging 30+ days / Repeat call'
  },
  {
    'Date': '11.09.2026',
    'Branch Name': 'Gandhinagar-CE',
    'No': 13,
    'Service Order No.': '4293847303',
    'ASC Job No': '4903760-01',
    'Created': '10.09.2026',
    'Assigned': '10.09.2026',
    'Assigned Time': '14:20',
    'Model': 'HW-Q600A',
    'Serial': 'SN987654333',
    'Wty Status': 'In Warranty',
    'VOC': 'Subwoofer wireless pairing disconnected',
    'REDO': 'N',
    'Risk Sensing': 'Normal',
    'RED': 'N',
    'High Priority': 'Normal',
    'Customer Name': 'Kunal Joshi',
    'City': 'Gandhinagar',
    'App Date': '11.09.2026',
    'App Time': '16:00 - 18:00',
    'Service Type': 'Carry In',
    'Status': 'Under Diagnosis',
    'Reason': 'Firmware update and re-syncing',
    'B2B': 'N',
    'Risk Reason': 'None'
  },
  {
    'Date': '11.09.2026',
    'Branch Name': 'Gurgaon-CE',
    'No': 14,
    'Service Order No.': '4293847304',
    'ASC Job No': '4903753-04',
    'Created': '07.09.2026',
    'Assigned': '07.09.2026',
    'Assigned Time': '09:30',
    'Model': 'LF24T350FHW',
    'Serial': 'SN987654334',
    'Wty Status': 'Out of Warranty',
    'VOC': 'Power adapter damaged / no power',
    'REDO': 'N',
    'Risk Sensing': 'Normal',
    'RED': 'N',
    'High Priority': 'Normal',
    'Customer Name': 'Ritu Saxena',
    'City': 'Gurgaon',
    'App Date': '08.09.2026',
    'App Time': '10:00 - 12:00',
    'Service Type': 'Customer Care',
    'Status': 'Under Repair',
    'Reason': 'Power supply unit testing',
    'B2B': 'N',
    'Risk Reason': 'None'
  },
  {
    'Date': '11.09.2026',
    'Branch Name': 'Surat-CE',
    'No': 15,
    'Service Order No.': '4293847305',
    'ASC Job No': '9225951-03',
    'Created': '02.09.2026',
    'Assigned': '02.09.2026',
    'Assigned Time': '13:00',
    'Model': 'WA70A4002GS',
    'Serial': 'SN987654335',
    'Wty Status': 'In Warranty',
    'VOC': 'Excessive vibration and unbalance error',
    'REDO': 'N',
    'Risk Sensing': 'Normal',
    'RED': 'N',
    'High Priority': 'Normal',
    'Customer Name': 'Hardik Trivedi',
    'City': 'Surat',
    'App Date': '03.09.2026',
    'App Time': '14:00 - 16:00',
    'Service Type': 'PICK-UP SERVICE',
    'Status': 'Picked Up',
    'Reason': 'Unit brought to workshop for suspension damper replacement',
    'B2B': 'N',
    'Risk Reason': 'None'
  }
];

function generateExcelHTML(rows, cols) {
  let trHeaders = cols.map(c => `<th style="background-color:#0f2e59;color:#ffffff;font-weight:bold;border:1px solid #cbd5e1;padding:6px 10px;text-align:left;">${c}</th>`).join('');
  let trRows = rows.map(r => {
    let tds = cols.map(c => {
      let val = r[c] !== undefined ? r[c] : '';
      return `<td style="border:1px solid #cbd5e1;padding:5px 8px;mso-number-format:'\\@';">${val}</td>`;
    }).join('');
    return `<tr>${tds}</tr>`;
  }).join('\n');

  return `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<!--[if gte mso 9]>
<xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>sample_data</x:Name>
    <x:WorksheetOptions>
     <x:DisplayGridlines/>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
 </x:ExcelWorkbook>
</xml>
<![endif]-->
<style>
  table { border-collapse: collapse; font-family: Calibri, 'Segoe UI', sans-serif; font-size: 11pt; }
</style>
</head>
<body>
<table>
  <thead>
    <tr>${trHeaders}</tr>
  </thead>
  <tbody>
    ${trRows}
  </tbody>
</table>
</body>
</html>`;
}

const content = generateExcelHTML(sampleRows, GSPN_COLUMNS);
fs.writeFileSync('scratch/sample_data.xls', content, 'utf8');
fs.writeFileSync('reports/sample_data.xls', content, 'utf8');
fs.writeFileSync('website_version_tools/sample_data.xls', content, 'utf8');
console.log('Successfully generated sample_data.xls across directories with 25 columns!');
